package com.satya.old.exception;

public class ExceptionTest1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			int a  =  5 / 0  ;
			
		} catch (Throwable e) {
			// TODO: handle exception
			e.printStackTrace();
		}

	}

}
